chats:
  local:
    enable: true
    format: '&8▸&r %luckperms_prefix%&r%player_displayname%&r &8› &f[message]'
    range: 150
    cooldownTicks: -1
  global:
    enable: false
    format: '{S}▸&r %luckperms_prefix%&r%player_displayname%&r {S}› &f[message]'
    range: -1
    symbol: '!'
    cooldownTicks: 40
broadcast_cooldown: 30
auto_messages_time: 90
command_replacements:
  enable: true
  format: "&8[/[command]]&r"
mentions:
  symbol: '@'
  in_chat_format: "{S}@[mentioned]&r"
  sound: UI_BUTTON_CLICK
spam_block:
  enable: false
  commands: []
swear_block:
  enable: true
  commands: []
  file: blocks/swears.yml # path to file
advertisement_block:
  enable: false
  file: blocks/ads.yml # path to file
  commands: []
caps_block:
  enable: true
  min_letters_for_check: 12
  min_caps_letter_percent: 60
  commands: []
replacement_words:
  enable: true
  file: blocks/replacements.yml # path to file
messages:
  reload:
    - "&aПлагин перезагружен!"
  noPermission:
    - "&cУ вас нет прав на это!"
  chatNotExists:
    - "&cЧат не существует!"
  chatIsBlocked:
    - "&cЧат [id] для вас заблокирован!"
  chatCooldown:
    - "&cПодождите еще [0] секунд..."
  playerIsOffline:
    - "&cИгрок оффлайн"
  noReply:
    - "&cНе найдено ни одно сообщения для переотправки"
  ignoreAll:
    enabling:
      - "&aВы начали игнорировать всех игроков!"
    disabling:
      - "&cВы перестали игнорировать всех игроков!"
  ignore:
    enabling:
      - "&aВы начали игнорировать игрока [player]!"
    disabling:
      - "&cВы перестали игнорировать игрока [player]!"
    youAreIgnored:
      - "&cИгрок [player] вас игнорирует!"
  spy:
    enabling:
      - "&aВы успешно включили режим шпиона!"
    disabling:
      - "&cВы успешно выключили режим шпиона!"
    format:
      - "{S}[ РШ ] [sender] &f-> {S}[recipient] &f» [message]"
  vanilla:
    onJoin: "" # [player]
    onQuit: "" # [player]
    onDeath: "" # [player]
    onDeathFromPlayer: "" # [player] [killer]
  private_messages:
    toMe:
      - "{S}[ ЛС ] [sender] &f-> {S}Вы &f» [message]"
    fromMe:
      - "{S}[ ЛС ] Вы &f-> {S}[recipient] &f» [message]"
    recipientIsYou:
      - "&cНельзя отправлять сообщение самому себе!"
  auto_messages: {}
    # example: "example text"
  broadcast:
    - "[BROADCAST] "
    - "[BROADCAST] {S}[ ! ] %player_displayname% &f» [message]"
    - "[BROADCAST] "
  spam_warn:
    - "&cПерестань спамить!"
  swear_warn:
    - "&cПерестань писать плохие слова!"
  caps_warn:
    - "&cПерестань капсить!"
  ads_warn:
    - "&cПерестань рекламить чужие проекты!"
  usage:
    satechat:
      - "&c/schat reload/send <chat>"
    privatemessage:
      - "&c/msg <player> <message>"
    reply:
      - "&c/reply <messagee>"
    broadcast:
      - "&c/bc <message>"